CATEGORY = (
	('', 'Select Category'),
	('SPORT', 'SPORT'),
	('BUSINESS', 'BUSINESS'),
	('FASHION', 'FASHION'),
	('POLITICS', 'POLITICS'),
	('ENTERTAINMENT', 'ENTERTAINMENT'),
	('EDUCATION', 'EDUCATION'),
	('SCIENCE&TECH', 'SCIENCE&TECH'),
)


GENDER = (
	('','Select Gender'),
	('FEMALE','FEMALE'),
	('MALE','MALE'),
)

BANK = (
	('', 'Select Bank'),
	('ACCESS BANK', 'ACCESS BANK'),
	('CITIBANK', 'CITIBANK'),
	('DIAMOND BANK', 'DIAMOND BANK'),
	('ECOBANK', 'ECOBANK'),
	('FIDELITY BANK', 'FIDELITY BANK'),
	('FIRST CITY MONUMENT BANK', 'FIRST CITY MONUMENT BANK'),
	('FIRST BANK', 'FIRST BANK'),
	('GUARANTY TRUST BANK', 'GUARANTY TRUST BANK'),
	('HERITAGE BANK', 'HERITAGE BANK'),
	('KEYSTONE BANK', 'KEYSTONE BANK'),
	('SKYE BANK', 'SKYE BANK'),
	('STANBIC IBTC', 'STANBIC IBTC'),
	('STANDARD CHARTERED BANK', 'STANDARD CHARTERED BANK'),
	('STERLING BANK', 'STERLING BANK'),
	('UNION BANK OF NIGERIA', 'UNION BANK OF NIGERIA'),
	('UNITED BANK OF AFRICA', 'UNITED BANK OF AFRICA'),
	('UNITY BANK', 'UNITY BANK'),
	('WEMA BANK', 'WEMA BANK'),
	('ZENITH BANK', 'ZENITH BANK'),
	
)