CATEGORY = (
	('', 'Select Category'),
	('SPORT', 'SPORT'),
	('BUSINESS', 'BUSINESS'),
	('FASHION', 'FASHION'),
	('POLITICS', 'POLITICS'),
	('ENTERTAINMENT', 'ENTERTAINMENT'),
	('EDUCATION', 'EDUCATION'),
	('SCIENCE&TECH', 'SCIENCE&TECH'),
)